In [25]:
import cv2
import time
import numpy as np
import pandas as pd

from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort

import motmetrics as mm

In [37]:


VIDEO_SOURCE   = r"D:/obj detection/train/MOT17-02-FRCNN/img1"

MODEL_PATH     = "yolov8l.pt"

TRACKER_TYPE   = "deepsort"     # "bytesort" or "deepsort"

SAVE_RESULT_PATH = f"{TRACKER_TYPE}_results.txt"

TARGET_CLASS   = 0

In [38]:
model = YOLO(MODEL_PATH)

if TRACKER_TYPE == "deepsort":
    tracker = DeepSort(
        max_age=50,
        
        n_init=1,
    
        max_cosine_distance=0.3,
        embedder="mobilenet",
        embedder_gpu=True
    )

In [39]:
import os

image_files = sorted([
    os.path.join(VIDEO_SOURCE, img)
    for img in os.listdir(VIDEO_SOURCE)
    if img.endswith(".jpg")
])

print("Total Frames:", len(image_files))

Total Frames: 600

In [40]:
tracking_results = []
frame_id = 0
total_fps = []

for image_path in image_files:

    frame = cv2.imread(image_path)

    if frame is None:
        continue

    frame_id += 1
    start_time = time.time()

   
    # BYTE TRACK
  
    if TRACKER_TYPE == "bytesort":
        results = model.track(
            frame,
            persist=True,
            imgsz=1280,
            conf=0.10,
            tracker="bytetrack.yaml",
            device="cuda",
            verbose=False
        )[0]

        if results.boxes.id is not None:

            boxes      = results.boxes.xyxy.int().cpu().tolist()
            track_ids  = results.boxes.id.int().cpu().tolist()
            classes    = results.boxes.cls.int().cpu().tolist()
            confs      = results.boxes.conf.cpu().tolist()

            print(
                f"Frame {frame_id}: "
                f"Detections={len(boxes)} "
                f"Tracks={len(track_ids)}"
            )

            for box, track_id, cls, conf in zip(boxes, track_ids, classes, confs):

                if cls != TARGET_CLASS:
                    continue

                x1, y1, x2, y2 = box
                w = x2 - x1
                h = y2 - y1

                tracking_results.append([
                    frame_id, track_id,
                    x1, y1, w, h,
                    round(conf, 4),
                    -1, -1, -1
                ])

                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
                cv2.putText(
                    frame,
                    f"{model.names[cls]} ID:{track_id}",
                    (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2
                )

  
    # DEEP SORT
   
    elif TRACKER_TYPE == "deepsort":

        results = model(
            frame,
            imgsz=1280,
            conf=0.10,  
            device="cuda",
            verbose=False
        )[0]

        detections = []

        for box in results.boxes:

            class_id   = int(box.cls[0].cpu().item())
            confidence = float(box.conf[0].cpu().item())

            if class_id != TARGET_CLASS:
                continue

            
         
            x1, y1, x2, y2 = box.xyxy[0].int().cpu().tolist()

            detections.append((
                [x1, y1, x2 - x1, y2 - y1],
                confidence,
                class_id
            ))

        tracks = tracker.update_tracks(detections, frame=frame)

        print(
            f"Frame {frame_id}: "
            f"Detections={len(detections)} "
            f"Tracks={len(tracks)}"
        )

        for track in tracks:

           
            if not track.is_confirmed():
                continue

           
            if track.time_since_update > 1:
                continue

            x1, y1, x2, y2 = map(int, track.to_ltrb())
            w = x2 - x1
            h = y2 - y1

            cls = getattr(track, "det_class",
                  getattr(track, "class_id", None))

          
            track_conf = track.det_conf if track.det_conf is not None else 1.0

            tracking_results.append([
                frame_id,
                track.track_id,
                x1, y1, w, h,
                round(float(track_conf), 4),
                -1, -1, -1
            ])

            cv2.rectangle(frame, (x1, y1), (x2, y2), (255, 0, 0), 2)
            cv2.putText(
                frame,
                f"{model.names[cls] if cls is not None else 'Person'} ID:{track.track_id}",
                (x1, y1 - 10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2
            )

    
    # FPS & DISPLAY

    fps = 1 / (time.time() - start_time)
    total_fps.append(fps)

    cv2.putText(
        frame,
        f"FPS: {int(fps)}",
        (20, 40),
        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2
    )
    cv2.putText(
    frame,
    f"Frame: {frame_id}",
    (20, 80),
    cv2.FONT_HERSHEY_SIMPLEX,
    0.8,
    (255, 255, 0),
    2
   )

    cv2.imshow("Tracking", frame)

    if cv2.waitKey(25) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()
print("Tracking Completed")

Frame 1: Detections=26 Tracks=26
Frame 2: Detections=24 Tracks=24
Frame 3: Detections=25 Tracks=26
Frame 4: Detections=30 Tracks=31
Frame 5: Detections=28 Tracks=29
Frame 6: Detections=28 Tracks=31
Frame 7: Detections=27 Tracks=30
Frame 8: Detections=29 Tracks=31
Frame 9: Detections=31 Tracks=33
Frame 10: Detections=28 Tracks=33
Frame 11: Detections=28 Tracks=33
Frame 12: Detections=32 Tracks=37
Frame 13: Detections=28 Tracks=36
Frame 14: Detections=28 Tracks=34
Frame 15: Detections=32 Tracks=40
Frame 16: Detections=30 Tracks=39
Frame 17: Detections=32 Tracks=43
Frame 18: Detections=25 Tracks=39
Frame 19: Detections=26 Tracks=40
Frame 20: Detections=29 Tracks=42
Frame 21: Detections=30 Tracks=44
Frame 22: Detections=32 Tracks=43
Frame 23: Detections=24 Tracks=42
Frame 24: Detections=26 Tracks=42
Frame 25: Detections=24 Tracks=42
Frame 26: Detections=23 Tracks=44
Frame 27: Detections=26 Tracks=45
Frame 28: Detections=28 Tracks=45
Frame 29: Detections=27 Tracks=45
Frame 30: Detections=28 Tracks=46
Frame 31: Detections=28 Tracks=45
Frame 32: Detections=25 Tracks=45
Frame 33: Detections=24 Tracks=46
Frame 34: Detections=24 Tracks=47
Frame 35: Detections=24 Tracks=45
Frame 36: Detections=28 Tracks=45
Frame 37: Detections=24 Tracks=46
Frame 38: Detections=29 Tracks=46
Frame 39: Detections=25 Tracks=47
Frame 40: Detections=22 Tracks=46
Frame 41: Detections=25 Tracks=46
Frame 42: Detections=26 Tracks=47
Frame 43: Detections=25 Tracks=47
Frame 44: Detections=29 Tracks=48
Frame 45: Detections=28 Tracks=48
Frame 46: Detections=25 Tracks=48
Frame 47: Detections=30 Tracks=49
Frame 48: Detections=30 Tracks=50
Frame 49: Detections=26 Tracks=50
Frame 50: Detections=21 Tracks=48
Frame 51: Detections=30 Tracks=50
Frame 52: Detections=26 Tracks=49
Frame 53: Detections=27 Tracks=49
Frame 54: Detections=29 Tracks=50
Frame 55: Detections=25 Tracks=49
Frame 56: Detections=28 Tracks=49
Frame 57: Detections=25 Tracks=49
Frame 58: Detections=24 Tracks=50
Frame 59: Detections=28 Tracks=52
Frame 60: Detections=27 Tracks=51
Frame 61: Detections=29 Tracks=51
Frame 62: Detections=29 Tracks=53
Frame 63: Detections=22 Tracks=52
Frame 64: Detections=22 Tracks=53
Frame 65: Detections=21 Tracks=52
Frame 66: Detections=22 Tracks=52
Frame 67: Detections=22 Tracks=52
Frame 68: Detections=21 Tracks=51
Frame 69: Detections=21 Tracks=51
Frame 70: Detections=22 Tracks=52
Frame 71: Detections=21 Tracks=51
Frame 72: Detections=22 Tracks=51
Frame 73: Detections=23 Tracks=51
Frame 74: Detections=23 Tracks=53
Frame 75: Detections=24 Tracks=52
Frame 76: Detections=20 Tracks=53
Frame 77: Detections=23 Tracks=52
Frame 78: Detections=26 Tracks=54
Frame 79: Detections=26 Tracks=53
Frame 80: Detections=21 Tracks=53
Frame 81: Detections=19 Tracks=53
Frame 82: Detections=25 Tracks=55
Frame 83: Detections=23 Tracks=53
Frame 84: Detections=22 Tracks=54
Frame 85: Detections=20 Tracks=54
Frame 86: Detections=19 Tracks=54
Frame 87: Detections=18 Tracks=54
Frame 88: Detections=19 Tracks=55
Frame 89: Detections=21 Tracks=55
Frame 90: Detections=25 Tracks=55
Frame 91: Detections=22 Tracks=54
Frame 92: Detections=23 Tracks=54
Frame 93: Detections=22 Tracks=54
Frame 94: Detections=21 Tracks=54
Frame 95: Detections=21 Tracks=54
Frame 96: Detections=23 Tracks=54
Frame 97: Detections=20 Tracks=54
Frame 98: Detections=21 Tracks=54
Frame 99: Detections=23 Tracks=53
Frame 100: Detections=20 Tracks=52
Frame 101: Detections=19 Tracks=52
Frame 102: Detections=23 Tracks=52
Frame 103: Detections=25 Tracks=52
Frame 104: Detections=26 Tracks=52
Frame 105: Detections=23 Tracks=52
Frame 106: Detections=22 Tracks=52
Frame 107: Detections=24 Tracks=52
Frame 108: Detections=25 Tracks=52
Frame 109: Detections=26 Tracks=53
Frame 110: Detections=26 Tracks=52
Frame 111: Detections=27 Tracks=52
Frame 112: Detections=25 Tracks=51
Frame 113: Detections=19 Tracks=51
Frame 114: Detections=23 Tracks=52
Frame 115: Detections=20 Tracks=51
Frame 116: Detections=20 Tracks=50
Frame 117: Detections=23 Tracks=51
Frame 118: Detections=22 Tracks=50
Frame 119: Detections=19 Tracks=50
Frame 120: Detections=20 Tracks=51
Frame 121: Detections=22 Tracks=52
Frame 122: Detections=18 Tracks=51
Frame 123: Detections=21 Tracks=49
Frame 124: Detections=26 Tracks=51
Frame 125: Detections=24 Tracks=49
Frame 126: Detections=18 Tracks=50
Frame 127: Detections=24 Tracks=50
Frame 128: Detections=28 Tracks=50
Frame 129: Detections=24 Tracks=49
Frame 130: Detections=25 Tracks=49
Frame 131: Detections=20 Tracks=49
Frame 132: Detections=22 Tracks=49
Frame 133: Detections=30 Tracks=49
Frame 134: Detections=22 Tracks=49
Frame 135: Detections=22 Tracks=49
Frame 136: Detections=24 Tracks=50
Frame 137: Detections=22 Tracks=50
Frame 138: Detections=24 Tracks=50
Frame 139: Detections=22 Tracks=50
Frame 140: Detections=26 Tracks=51
Frame 141: Detections=23 Tracks=51
Frame 142: Detections=27 Tracks=50
Frame 143: Detections=26 Tracks=50
Frame 144: Detections=23 Tracks=51
Frame 145: Detections=25 Tracks=52
Frame 146: Detections=24 Tracks=50
Frame 147: Detections=24 Tracks=50
Frame 148: Detections=25 Tracks=50
Frame 149: Detections=24 Tracks=50
Frame 150: Detections=22 Tracks=50
Frame 151: Detections=22 Tracks=50
Frame 152: Detections=22 Tracks=50
Frame 153: Detections=27 Tracks=51
Frame 154: Detections=23 Tracks=51
Frame 155: Detections=24 Tracks=51
Frame 156: Detections=21 Tracks=51
Frame 157: Detections=25 Tracks=51
Frame 158: Detections=21 Tracks=51
Frame 159: Detections=24 Tracks=51
Frame 160: Detections=27 Tracks=51
Frame 161: Detections=25 Tracks=51
Frame 162: Detections=26 Tracks=50
Frame 163: Detections=23 Tracks=50
Frame 164: Detections=22 Tracks=51
Frame 165: Detections=22 Tracks=50
Frame 166: Detections=23 Tracks=50
Frame 167: Detections=22 Tracks=50
Frame 168: Detections=25 Tracks=51
Frame 169: Detections=23 Tracks=49
Frame 170: Detections=21 Tracks=50
Frame 171: Detections=19 Tracks=49
Frame 172: Detections=27 Tracks=49
Frame 173: Detections=28 Tracks=49
Frame 174: Detections=27 Tracks=48
Frame 175: Detections=26 Tracks=50
Frame 176: Detections=27 Tracks=49
Frame 177: Detections=27 Tracks=50
Frame 178: Detections=21 Tracks=48
Frame 179: Detections=21 Tracks=49
Frame 180: Detections=18 Tracks=48
Frame 181: Detections=19 Tracks=48
Frame 182: Detections=20 Tracks=48
Frame 183: Detections=16 Tracks=48
Frame 184: Detections=15 Tracks=48
Frame 185: Detections=17 Tracks=48
Frame 186: Detections=20 Tracks=49
Frame 187: Detections=17 Tracks=48
Frame 188: Detections=21 Tracks=48
Frame 189: Detections=23 Tracks=49
Frame 190: Detections=21 Tracks=48
Frame 191: Detections=23 Tracks=48
Frame 192: Detections=22 Tracks=48
Frame 193: Detections=20 Tracks=49
Frame 194: Detections=17 Tracks=48
Frame 195: Detections=18 Tracks=48
Frame 196: Detections=20 Tracks=49
Frame 197: Detections=22 Tracks=49
Frame 198: Detections=20 Tracks=49
Frame 199: Detections=20 Tracks=49
Frame 200: Detections=21 Tracks=50
Frame 201: Detections=21 Tracks=49
Frame 202: Detections=18 Tracks=49
Frame 203: Detections=24 Tracks=49
Frame 204: Detections=29 Tracks=52
Frame 205: Detections=26 Tracks=51
Frame 206: Detections=21 Tracks=50
Frame 207: Detections=21 Tracks=49
Frame 208: Detections=23 Tracks=49
Frame 209: Detections=24 Tracks=50
Frame 210: Detections=24 Tracks=50
Frame 211: Detections=26 Tracks=50
Frame 212: Detections=27 Tracks=51
Frame 213: Detections=23 Tracks=50
Frame 214: Detections=20 Tracks=50
Frame 215: Detections=22 Tracks=50
Frame 216: Detections=24 Tracks=50
Frame 217: Detections=21 Tracks=50
Frame 218: Detections=21 Tracks=51
Frame 219: Detections=20 Tracks=49
Frame 220: Detections=20 Tracks=49
Frame 221: Detections=19 Tracks=50
Frame 222: Detections=22 Tracks=50
Frame 223: Detections=23 Tracks=50
Frame 224: Detections=23 Tracks=51
Frame 225: Detections=22 Tracks=51
Frame 226: Detections=22 Tracks=51
Frame 227: Detections=22 Tracks=49
Frame 228: Detections=23 Tracks=49
Frame 229: Detections=23 Tracks=49
Frame 230: Detections=24 Tracks=49
Frame 231: Detections=24 Tracks=51
Frame 232: Detections=23 Tracks=50
Frame 233: Detections=27 Tracks=49
Frame 234: Detections=25 Tracks=51
Frame 235: Detections=26 Tracks=50
Frame 236: Detections=28 Tracks=49
Frame 237: Detections=27 Tracks=50
Frame 238: Detections=27 Tracks=52
Frame 239: Detections=29 Tracks=52
Frame 240: Detections=24 Tracks=51
Frame 241: Detections=26 Tracks=51
Frame 242: Detections=26 Tracks=51
Frame 243: Detections=31 Tracks=53
Frame 244: Detections=27 Tracks=51
Frame 245: Detections=26 Tracks=51
Frame 246: Detections=26 Tracks=51
Frame 247: Detections=29 Tracks=52
Frame 248: Detections=34 Tracks=53
Frame 249: Detections=33 Tracks=52
Frame 250: Detections=30 Tracks=52
Frame 251: Detections=27 Tracks=52
Frame 252: Detections=31 Tracks=52
Frame 253: Detections=29 Tracks=52
Frame 254: Detections=34 Tracks=52
Frame 255: Detections=28 Tracks=51
Frame 256: Detections=29 Tracks=53
Frame 257: Detections=26 Tracks=52
Frame 258: Detections=28 Tracks=52
Frame 259: Detections=26 Tracks=53
Frame 260: Detections=28 Tracks=53
Frame 261: Detections=27 Tracks=54
Frame 262: Detections=26 Tracks=54
Frame 263: Detections=28 Tracks=52
Frame 264: Detections=26 Tracks=53
Frame 265: Detections=24 Tracks=52
Frame 266: Detections=25 Tracks=52
Frame 267: Detections=25 Tracks=51
Frame 268: Detections=24 Tracks=50
Frame 269: Detections=25 Tracks=50
Frame 270: Detections=23 Tracks=51
Frame 271: Detections=25 Tracks=53
Frame 272: Detections=27 Tracks=51
Frame 273: Detections=28 Tracks=49
Frame 274: Detections=28 Tracks=50
Frame 275: Detections=28 Tracks=50
Frame 276: Detections=29 Tracks=49
Frame 277: Detections=30 Tracks=49
Frame 278: Detections=25 Tracks=49
Frame 279: Detections=31 Tracks=50
Frame 280: Detections=32 Tracks=51
Frame 281: Detections=30 Tracks=52
Frame 282: Detections=30 Tracks=51
Frame 283: Detections=33 Tracks=52
Frame 284: Detections=28 Tracks=51
Frame 285: Detections=30 Tracks=54
Frame 286: Detections=32 Tracks=54
Frame 287: Detections=30 Tracks=53
Frame 288: Detections=28 Tracks=54
Frame 289: Detections=27 Tracks=55
Frame 290: Detections=26 Tracks=55
Frame 291: Detections=26 Tracks=55
Frame 292: Detections=28 Tracks=55
Frame 293: Detections=25 Tracks=54
Frame 294: Detections=27 Tracks=54
Frame 295: Detections=26 Tracks=54
Frame 296: Detections=31 Tracks=55
Frame 297: Detections=36 Tracks=57
Frame 298: Detections=30 Tracks=55
Frame 299: Detections=31 Tracks=58
Frame 300: Detections=33 Tracks=58
Frame 301: Detections=30 Tracks=58
Frame 302: Detections=27 Tracks=58
Frame 303: Detections=31 Tracks=60
Frame 304: Detections=27 Tracks=60
Frame 305: Detections=27 Tracks=60
Frame 306: Detections=28 Tracks=60
Frame 307: Detections=30 Tracks=61
Frame 308: Detections=27 Tracks=60
Frame 309: Detections=30 Tracks=61
Frame 310: Detections=25 Tracks=60
Frame 311: Detections=30 Tracks=60
Frame 312: Detections=24 Tracks=60
Frame 313: Detections=26 Tracks=60
Frame 314: Detections=32 Tracks=60
Frame 315: Detections=33 Tracks=60
Frame 316: Detections=32 Tracks=59
Frame 317: Detections=34 Tracks=60
Frame 318: Detections=33 Tracks=63
Frame 319: Detections=29 Tracks=61
Frame 320: Detections=27 Tracks=60
Frame 321: Detections=30 Tracks=62
Frame 322: Detections=29 Tracks=61
Frame 323: Detections=27 Tracks=60
Frame 324: Detections=30 Tracks=60
Frame 325: Detections=26 Tracks=60
Frame 326: Detections=28 Tracks=62
Frame 327: Detections=25 Tracks=60
Frame 328: Detections=27 Tracks=61
Frame 329: Detections=29 Tracks=60
Frame 330: Detections=31 Tracks=62
Frame 331: Detections=27 Tracks=62
Frame 332: Detections=31 Tracks=62
Frame 333: Detections=31 Tracks=61
Frame 334: Detections=27 Tracks=62
Frame 335: Detections=26 Tracks=61
Frame 336: Detections=29 Tracks=62
Frame 337: Detections=27 Tracks=61
Frame 338: Detections=28 Tracks=61
Frame 339: Detections=32 Tracks=63
Frame 340: Detections=29 Tracks=63
Frame 341: Detections=26 Tracks=63
Frame 342: Detections=27 Tracks=62
Frame 343: Detections=30 Tracks=63
Frame 344: Detections=30 Tracks=63
Frame 345: Detections=31 Tracks=63
Frame 346: Detections=36 Tracks=65
Frame 347: Detections=30 Tracks=63
Frame 348: Detections=32 Tracks=64
Frame 349: Detections=30 Tracks=64
Frame 350: Detections=28 Tracks=63
Frame 351: Detections=28 Tracks=63
Frame 352: Detections=23 Tracks=62
Frame 353: Detections=32 Tracks=64
Frame 354: Detections=27 Tracks=62
Frame 355: Detections=26 Tracks=63
Frame 356: Detections=25 Tracks=62
Frame 357: Detections=25 Tracks=63
Frame 358: Detections=28 Tracks=63
Frame 359: Detections=25 Tracks=62
Frame 360: Detections=30 Tracks=64
Frame 361: Detections=28 Tracks=63
Frame 362: Detections=29 Tracks=63
Frame 363: Detections=30 Tracks=64
Frame 364: Detections=29 Tracks=63
Frame 365: Detections=25 Tracks=63
Frame 366: Detections=26 Tracks=63
Frame 367: Detections=26 Tracks=63
Frame 368: Detections=26 Tracks=63
Frame 369: Detections=30 Tracks=64
Frame 370: Detections=26 Tracks=62
Frame 371: Detections=27 Tracks=62
Frame 372: Detections=27 Tracks=62
Frame 373: Detections=25 Tracks=63
Frame 374: Detections=23 Tracks=63
Frame 375: Detections=22 Tracks=61
Frame 376: Detections=28 Tracks=60
Frame 377: Detections=24 Tracks=61
Frame 378: Detections=24 Tracks=61
Frame 379: Detections=23 Tracks=62
Frame 380: Detections=25 Tracks=62
Frame 381: Detections=21 Tracks=62
Frame 382: Detections=18 Tracks=61
Frame 383: Detections=23 Tracks=62
Frame 384: Detections=23 Tracks=62
Frame 385: Detections=22 Tracks=61
Frame 386: Detections=22 Tracks=61
Frame 387: Detections=22 Tracks=62
Frame 388: Detections=24 Tracks=62
Frame 389: Detections=26 Tracks=61
Frame 390: Detections=26 Tracks=60
Frame 391: Detections=23 Tracks=59
Frame 392: Detections=23 Tracks=60
Frame 393: Detections=25 Tracks=60
Frame 394: Detections=20 Tracks=60
Frame 395: Detections=23 Tracks=60
Frame 396: Detections=22 Tracks=60
Frame 397: Detections=23 Tracks=59
Frame 398: Detections=22 Tracks=59
Frame 399: Detections=17 Tracks=59
Frame 400: Detections=19 Tracks=59
Frame 401: Detections=23 Tracks=59
Frame 402: Detections=21 Tracks=59
Frame 403: Detections=18 Tracks=58
Frame 404: Detections=22 Tracks=59
Frame 405: Detections=20 Tracks=58
Frame 406: Detections=27 Tracks=59
Frame 407: Detections=20 Tracks=58
Frame 408: Detections=24 Tracks=60
Frame 409: Detections=20 Tracks=59
Frame 410: Detections=23 Tracks=60
Frame 411: Detections=19 Tracks=59
Frame 412: Detections=21 Tracks=59
Frame 413: Detections=19 Tracks=59
Frame 414: Detections=19 Tracks=57
Frame 415: Detections=18 Tracks=57
Frame 416: Detections=20 Tracks=59
Frame 417: Detections=20 Tracks=58
Frame 418: Detections=22 Tracks=58
Frame 419: Detections=22 Tracks=58
Frame 420: Detections=21 Tracks=58
Frame 421: Detections=20 Tracks=58
Frame 422: Detections=22 Tracks=60
Frame 423: Detections=21 Tracks=58
Frame 424: Detections=21 Tracks=57
Frame 425: Detections=22 Tracks=58
Frame 426: Detections=22 Tracks=61
Frame 427: Detections=20 Tracks=59
Frame 428: Detections=20 Tracks=59
Frame 429: Detections=19 Tracks=61
Frame 430: Detections=19 Tracks=61
Frame 431: Detections=20 Tracks=60
Frame 432: Detections=19 Tracks=60
Frame 433: Detections=22 Tracks=61
Frame 434: Detections=21 Tracks=60
Frame 435: Detections=21 Tracks=60
Frame 436: Detections=20 Tracks=60
Frame 437: Detections=20 Tracks=59
Frame 438: Detections=21 Tracks=59
Frame 439: Detections=20 Tracks=60
Frame 440: Detections=18 Tracks=61
Frame 441: Detections=17 Tracks=59
Frame 442: Detections=20 Tracks=59
Frame 443: Detections=16 Tracks=59
Frame 444: Detections=20 Tracks=58
Frame 445: Detections=20 Tracks=58
Frame 446: Detections=24 Tracks=61
Frame 447: Detections=21 Tracks=61
Frame 448: Detections=21 Tracks=60
Frame 449: Detections=26 Tracks=61
Frame 450: Detections=24 Tracks=62
Frame 451: Detections=25 Tracks=62
Frame 452: Detections=28 Tracks=62
Frame 453: Detections=25 Tracks=62
Frame 454: Detections=24 Tracks=62
Frame 455: Detections=27 Tracks=64
Frame 456: Detections=29 Tracks=64
Frame 457: Detections=29 Tracks=66
Frame 458: Detections=22 Tracks=64
Frame 459: Detections=24 Tracks=65
Frame 460: Detections=25 Tracks=67
Frame 461: Detections=22 Tracks=66
Frame 462: Detections=24 Tracks=66
Frame 463: Detections=22 Tracks=66
Frame 464: Detections=27 Tracks=67
Frame 465: Detections=28 Tracks=69
Frame 466: Detections=23 Tracks=68
Frame 467: Detections=27 Tracks=69
Frame 468: Detections=26 Tracks=68
Frame 469: Detections=33 Tracks=70
Frame 470: Detections=29 Tracks=68
Frame 471: Detections=30 Tracks=69
Frame 472: Detections=29 Tracks=69
Frame 473: Detections=39 Tracks=71
Frame 474: Detections=33 Tracks=70
Frame 475: Detections=34 Tracks=70
Frame 476: Detections=34 Tracks=69
Frame 477: Detections=32 Tracks=70
Frame 478: Detections=30 Tracks=69
Frame 479: Detections=31 Tracks=69
Frame 480: Detections=32 Tracks=69
Frame 481: Detections=34 Tracks=71
Frame 482: Detections=32 Tracks=69
Frame 483: Detections=34 Tracks=71
Frame 484: Detections=32 Tracks=71
Frame 485: Detections=29 Tracks=71
Frame 486: Detections=31 Tracks=70
Frame 487: Detections=34 Tracks=71
Frame 488: Detections=32 Tracks=72
Frame 489: Detections=37 Tracks=76
Frame 490: Detections=33 Tracks=73
Frame 491: Detections=30 Tracks=74
Frame 492: Detections=32 Tracks=76
Frame 493: Detections=30 Tracks=76
Frame 494: Detections=27 Tracks=75
Frame 495: Detections=24 Tracks=75
Frame 496: Detections=26 Tracks=74
Frame 497: Detections=27 Tracks=74
Frame 498: Detections=26 Tracks=73
Frame 499: Detections=29 Tracks=73
Frame 500: Detections=27 Tracks=73
Frame 501: Detections=27 Tracks=73
Frame 502: Detections=27 Tracks=74
Frame 503: Detections=30 Tracks=73
Frame 504: Detections=33 Tracks=72
Frame 505: Detections=30 Tracks=71
Frame 506: Detections=29 Tracks=72
Frame 507: Detections=27 Tracks=72
Frame 508: Detections=25 Tracks=71
Frame 509: Detections=33 Tracks=71
Frame 510: Detections=28 Tracks=70
Frame 511: Detections=24 Tracks=70
Frame 512: Detections=26 Tracks=71
Frame 513: Detections=26 Tracks=70
Frame 514: Detections=25 Tracks=70
Frame 515: Detections=27 Tracks=70
Frame 516: Detections=24 Tracks=70
Frame 517: Detections=23 Tracks=69
Frame 518: Detections=25 Tracks=70
Frame 519: Detections=24 Tracks=69
Frame 520: Detections=23 Tracks=69
Frame 521: Detections=25 Tracks=69
Frame 522: Detections=26 Tracks=69
Frame 523: Detections=27 Tracks=69
Frame 524: Detections=24 Tracks=68
Frame 525: Detections=24 Tracks=67
Frame 526: Detections=26 Tracks=67
Frame 527: Detections=22 Tracks=67
Frame 528: Detections=23 Tracks=67
Frame 529: Detections=23 Tracks=67
Frame 530: Detections=22 Tracks=67
Frame 531: Detections=19 Tracks=67
Frame 532: Detections=18 Tracks=67
Frame 533: Detections=19 Tracks=66
Frame 534: Detections=20 Tracks=65
Frame 535: Detections=21 Tracks=65
Frame 536: Detections=20 Tracks=65
Frame 537: Detections=19 Tracks=64
Frame 538: Detections=20 Tracks=64
Frame 539: Detections=18 Tracks=64
Frame 540: Detections=19 Tracks=64
Frame 541: Detections=15 Tracks=62
Frame 542: Detections=17 Tracks=62
Frame 543: Detections=19 Tracks=60
Frame 544: Detections=18 Tracks=58
Frame 545: Detections=19 Tracks=58
Frame 546: Detections=19 Tracks=58
Frame 547: Detections=18 Tracks=58
Frame 548: Detections=20 Tracks=59
Frame 549: Detections=21 Tracks=59
Frame 550: Detections=22 Tracks=58
Frame 551: Detections=23 Tracks=57
Frame 552: Detections=21 Tracks=56
Frame 553: Detections=20 Tracks=57
Frame 554: Detections=19 Tracks=57
Frame 555: Detections=19 Tracks=56
Frame 556: Detections=21 Tracks=54
Frame 557: Detections=22 Tracks=54
Frame 558: Detections=21 Tracks=54
Frame 559: Detections=19 Tracks=54
Frame 560: Detections=22 Tracks=55
Frame 561: Detections=18 Tracks=52
Frame 562: Detections=18 Tracks=53
Frame 563: Detections=22 Tracks=53
Frame 564: Detections=24 Tracks=55
Frame 565: Detections=23 Tracks=53
Frame 566: Detections=24 Tracks=53
Frame 567: Detections=24 Tracks=54
Frame 568: Detections=22 Tracks=53
Frame 569: Detections=24 Tracks=53
Frame 570: Detections=24 Tracks=53
Frame 571: Detections=24 Tracks=53
Frame 572: Detections=20 Tracks=53
Frame 573: Detections=22 Tracks=53
Frame 574: Detections=26 Tracks=53

In [41]:
df = pd.DataFrame(tracking_results)

df.to_csv(
    SAVE_RESULT_PATH,
    header=False,
    index=False
)
print("Rows written:", len(tracking_results))
print("Results saved to:", SAVE_RESULT_PATH)

Rows written: 16107
Results saved to: deepsort_results.txt

In [42]:
avg_fps = sum(total_fps) / len(total_fps)
print("Average FPS:", round(avg_fps, 2))

Average FPS: 2.58

In [43]:
gt_path = r"D:/obj detection/train/MOT17-02-FRCNN/gt/gt.txt"

gt = pd.read_csv(gt_path, header=None)

gt.columns = ["frame", "id", "x", "y", "w", "h", "conf", "class", "visibility"]


gt = gt[
    (gt["class"] == 1) &
    (gt["conf"]  == 1)
]

print("GT rows:", len(gt))
gt.head()

GT rows: 18581

     frame  id     x    y    w    h  conf  class  visibility
600      1   2  1338  418  167  379     1      1         1.0
601      2   2  1342  417  168  380     1      1         1.0
602      3   2  1346  417  170  380     1      1         1.0
603      4   2  1351  417  171  381     1      1         1.0
604      5   2  1355  417  173  381     1      1         1.0

In [44]:
pred = pd.read_csv(SAVE_RESULT_PATH, header=None)

pred.columns = ["frame", "id", "x", "y", "w", "h", "conf", "a", "b", "c"]

print("Pred rows:", len(pred))
pred.head()

Pred rows: 16107

   frame  id     x    y    w    h    conf  a  b  c
0      2   1  1345  419  166  373  0.8917 -1 -1 -1
1      2   2   583  444   89  263  0.8809 -1 -1 -1
2      2   3   440  443  112  280  0.8638 -1 -1 -1
3      2   4  1433  430  170  337  0.7536 -1 -1 -1
4      2   5  1015  428   43  101  0.8206 -1 -1 -1

In [45]:
print("GT objects   :", len(gt))
print("Pred objects :", len(pred))
print()
print("GT unique frames  :", gt["frame"].nunique())
print("Pred unique frames:", pred["frame"].nunique())
print()

GT objects   : 18581
Pred objects : 16107

GT unique frames  : 600
Pred unique frames: 599

In [46]:
acc = mm.MOTAccumulator(auto_id=True)


all_frames = sorted(
    set(gt["frame"].unique()) | set(pred["frame"].unique())
)

for frame in all_frames:

    gt_frame   = gt[gt["frame"]     == frame]
    pred_frame = pred[pred["frame"] == frame]

    gt_ids   = gt_frame["id"].tolist()
    pred_ids = pred_frame["id"].tolist()

    gt_boxes   = gt_frame[["x", "y", "w", "h"]].values
    pred_boxes = pred_frame[["x", "y", "w", "h"]].values

   
    distance_matrix = mm.distances.iou_matrix(
        gt_boxes,
        pred_boxes,
        max_iou=0.5
    )

    acc.update(
        gt_ids,
        pred_ids,
        distance_matrix
    )

mh = mm.metrics.create()

summary = mh.compute(
    acc,
    metrics=[
        "mota",
        "idf1",
        "num_switches",
        "precision",
        "recall",
        "num_false_positives",
        "num_misses"
    ],
    name=TRACKER_TYPE
)

print(summary)

              mota     idf1  num_switches  precision    recall  \
deepsort  0.094613  0.29428           307   0.564103  0.488994

          num_false_positives  num_misses
deepsort                 7021        9495

In [13]:
summary.to_csv(f"{TRACKER_TYPE}_evaluation.csv")
print("Evaluation saved to:", f"{TRACKER_TYPE}_evaluation.csv")

Evaluation saved to: deepsort_evaluation.csv